#https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html

alert_is_present()
all_of(*expected_conditions)
any_of(*expected_conditions)
element_attribute_to_include(locator, attribute_)
element_located_selection_state_to_be(…)
element_located_to_be_selected(locator)
element_selection_state_to_be(element, …)
element_to_be_clickable(mark)
element_to_be_selected(element)
frame_to_be_available_and_switch_to_it(locator)
invisibility_of_element(element)
invisibility_of_element_located(locator)
new_window_is_opened(current_handles)
none_of(*expected_conditions)
number_of_windows_to_be(num_windows)
presence_of_all_elements_located(locator)
presence_of_element_located(locator)
staleness_of(element)
text_to_be_present_in_element(locator, text_)
text_to_be_present_in_element_attribute(…)
text_to_be_present_in_element_value(locator, …)
title_contains(title)
title_is(title)
url_changes(url)
url_contains(url)
url_matches(pattern)
url_to_be(url)
visibility_of(element)
visibility_of_all_elements_located(locator)
visibility_of_any_elements_located(locator)
visibility_of_element_located(locator)
